version: '3'

services: 
  network-api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:pass@db:5432/mydatabase"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Ensure this is correct
    volumes:
      - db_data:/var/lib/postgresql/data
  prisma-migrate:
    build: .
    command: ["npx", "prisma", "migrate", "dev"]
    environment:
      DATABASE_URL: "postgresql://postgres:pass@db:5432/mydatabase?schema=public"
    depends_on:
      - db
    restart: "no"

volumes:
  db_data: 